### ISSUE TITLE
Feature: Access SVGs or SVG sprite in project

### ISSUE THREAD

**Issue by missmatsuko** [monachilada/craft-svgicons#1]
So I thought this was the Craft 3 version of https://github.com/fyrebase/svg-icons since it has the same name, but the functionality seems to be different.

This one allows users to pick icons from a couple specific icon sets, but the Craft 2 one pulls icons from any set of SVGs: https://github.com/fyrebase/svg-icons#svg-icons-overview

Can there be an option to pull from SVGs or an SVG sprite in the same project?

**Comment by missmatsuko** [comment]
Actually nevermind, I thought it had a field for picking icons but I guess it's not that at all!

**Comment by monachilada** [comment]
The ability to add your own icons would definitely be useful, but you're right in that it's no exactly what this plugin is trying to achieve. The main reason was a quick shortcut for inlining SVGs as both those libraries are designed for, so that CSS can be used to more easily control and customise their appearance.

Still, I could see a field being useful, if only to give a visual preview of which icon you are picking. But in the end, on the template side the field only needs to be a string with the specific library filter appended to it.
